// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCore.EntityFrameworkCore;

namespace OCore.Migrator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OCore.Article.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.Property<int>("Click");

                    b.Property<string>("Content");

                    b.Property<string>("CoverImg");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<bool>("IsHot");

                    b.Property<bool>("IsRed");

                    b.Property<bool>("IsTop");

                    b.Property<int>("LikeCount");

                    b.Property<string>("SeoDescription");

                    b.Property<string>("SeoKeywords");

                    b.Property<string>("SeoTitle");

                    b.Property<int>("Sort");

                    b.Property<string>("Source")
                        .HasMaxLength(256);

                    b.Property<int>("Status");

                    b.Property<string>("Tags");

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("OCore_Articles");
                });

            modelBuilder.Entity("OCore.Article.TencentVod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppId");

                    b.Property<string>("CategoryName");

                    b.Property<int>("Click");

                    b.Property<string>("CoverImg");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<string>("FileId");

                    b.Property<bool>("IsHot");

                    b.Property<bool>("IsRed");

                    b.Property<bool>("IsTop");

                    b.Property<int>("LikeCount");

                    b.Property<int>("Sort");

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("OCore_TencentVods");
                });

            modelBuilder.Entity("OCore.Environment.Shell.Descriptor.Models.ShellDescriptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SerialNumber");

                    b.HasKey("Id");

                    b.ToTable("ShellDescriptor");
                });

            modelBuilder.Entity("OCore.Environment.Shell.Descriptor.Models.ShellFeature", b =>
                {
                    b.Property<string>("Id");

                    b.Property<int?>("ShellDescriptorId");

                    b.HasKey("Id");

                    b.HasIndex("ShellDescriptorId");

                    b.ToTable("ShellFeature");
                });

            modelBuilder.Entity("OCore.Environment.Shell.Descriptor.Models.ShellParameter", b =>
                {
                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.Property<string>("Component");

                    b.Property<int?>("ShellDescriptorId");

                    b.HasKey("Name", "Value", "Component");

                    b.HasIndex("ShellDescriptorId");

                    b.ToTable("ShellParameter");
                });

            modelBuilder.Entity("OCore.Environment.Shell.State.ShellFeatureState", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EnableState");

                    b.Property<int>("InstallState");

                    b.Property<int?>("ShellStateId");

                    b.HasKey("Id");

                    b.HasIndex("ShellStateId");

                    b.ToTable("ShellFeatureState");
                });

            modelBuilder.Entity("OCore.Environment.Shell.State.ShellState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("ShellState");
                });

            modelBuilder.Entity("OCore.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("OCore_Roles");
                });

            modelBuilder.Entity("OCore.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("OCore_RoleClaims");
                });

            modelBuilder.Entity("OCore.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName")
                        .HasMaxLength(256);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("OCore_Users");
                });

            modelBuilder.Entity("OCore.Identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OCore_UserClaims");
                });

            modelBuilder.Entity("OCore.Identity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("OCore_UserLogins");
                });

            modelBuilder.Entity("OCore.Identity.UserRole", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("OCore_UserRoles");
                });

            modelBuilder.Entity("OCore.Identity.UserToken", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("OCore_UserTokens");
                });

            modelBuilder.Entity("OCore.Recipes.Entitys.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExecutionId");

                    b.Property<string>("JsonValue");

                    b.HasKey("Id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("OCore.Settings.SiteSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseUrl");

                    b.Property<string>("Calendar");

                    b.Property<string>("Culture");

                    b.Property<string>("HomeRoute_Action");

                    b.Property<string>("HomeRoute_Area");

                    b.Property<string>("HomeRoute_Controller");

                    b.Property<int>("MaxPageSize");

                    b.Property<int>("MaxPagedCount");

                    b.Property<int>("PageSize");

                    b.Property<int>("ResourceDebugMode");

                    b.Property<string>("SiteName");

                    b.Property<string>("SiteSalt");

                    b.Property<string>("SuperUser");

                    b.Property<string>("TimeZone");

                    b.Property<bool>("UseCdn");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("OCore.Environment.Shell.Descriptor.Models.ShellFeature", b =>
                {
                    b.HasOne("OCore.Environment.Shell.Descriptor.Models.ShellDescriptor")
                        .WithMany("Features")
                        .HasForeignKey("ShellDescriptorId");
                });

            modelBuilder.Entity("OCore.Environment.Shell.Descriptor.Models.ShellParameter", b =>
                {
                    b.HasOne("OCore.Environment.Shell.Descriptor.Models.ShellDescriptor")
                        .WithMany("Parameters")
                        .HasForeignKey("ShellDescriptorId");
                });

            modelBuilder.Entity("OCore.Environment.Shell.State.ShellFeatureState", b =>
                {
                    b.HasOne("OCore.Environment.Shell.State.ShellState")
                        .WithMany("Features")
                        .HasForeignKey("ShellStateId");
                });

            modelBuilder.Entity("OCore.Identity.RoleClaim", b =>
                {
                    b.HasOne("OCore.Identity.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OCore.Identity.UserClaim", b =>
                {
                    b.HasOne("OCore.Identity.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OCore.Identity.UserLogin", b =>
                {
                    b.HasOne("OCore.Identity.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OCore.Identity.UserRole", b =>
                {
                    b.HasOne("OCore.Identity.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OCore.Identity.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OCore.Identity.UserToken", b =>
                {
                    b.HasOne("OCore.Identity.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
